### ISSUE TITLE
Taiwan to change the ID format for foreigners in 2021

### ISSUE THREAD

**Issue by slawa-dev** [Edditoria/validid#9]
Old format will be still supported for another 10 years, but new IDs will have new format.

1st digit: geographic letter code as normal (A=taipei, …)
2nd digit: male(8)/female(9)
3rd digit: 0-6 for foreign nationals or stateless, 7 for NWOHR, 8 for Hong Kong & Macao, 9 for China

https://www.immigration.gov.tw/media/59037/004.png

https://www.immigration.gov.tw/5385/7445/238440/

**Comment by Edditoria** [comment]
Thanks for your information. I will update this in Dec.

**Comment by Edditoria** [comment]
Hi,

This package is updated to v2.2.0 (commit: 81b3131 ). Now `validid.twrc(id)` will validate both new and old ID.

Please `npm update validid`.

Also, you can now `import twrc from 'validid/esm/index.mjs'`. Same for other modules.

Happy coding :smile_cat:

**Comment by slawa-dev** [comment]
https://www.youtube.com/watch?v=-6qCkzeV8AM
